FROM python:3.11
ENV PYTHONUNBUFFERED=1
RUN mkdir /app
WORKDIR /app

# Install dependencies

# RUN wget https://github.com/draeger-lab/ModelPolisher/releases/download/1.7/ModelPolisher-1.7.jar

RUN apt-get update && apt-get install -y \
  libxml2-dev postgresql-client

WORKDIR /server

RUN apt-get install -y nodejs npm
RUN npm install -g sass

WORKDIR /app

COPY requirements.txt /app/
RUN pip install -r requirements.txt

RUN git clone https://github.com/pascalaldo/bigg_models_data.git bigg_models_data

RUN git clone https://github.com/pascalaldo/biggr_maps.git biggr_maps
WORKDIR /app/biggr_maps/
RUN git pull && git reset --hard 54c6d88
RUN python setup.py install
WORKDIR /app

# RUN git clone -b api https://github.com/pascalaldo/cobradb.git cobradb
# WORKDIR /app/cobradb/
# RUN git pull && git reset --hard 6082ebb

WORKDIR /server

CMD ["bin/server-entrypoint-dev.sh"]
